[package]
name = "check-have-i-been-pwned"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.51", features = ["derive"] }
hex = "0.4.3"
indicatif = { version = "0.18.3", features = ["rayon"] }
rayon = "1.10.0"
serde_json = "1.0.140"
sha1 = "0.10.6"
